export const ACTION_TYPE = {
	LOGOUT: "LOGOUT",
	SET_USER: "SET_USER",
	OPEN_MODAL: "OPEN_MODAL",
	CLOSE_MODAL: "CLOSE_MODAL",
	SET_PRODUCT: "SET_PRODUCT",
	SET_PRODUCT_IS_LOADING: "SET_PRODUCT_IS_LOADING",
	CREATE_COMMENT: "CREATE_COMMENT",
	DELETE_COMMENT: "DELETE_COMMENT",
};
