export const ACTION_TYPE = {
	LOGOUT: "LOGOUT",
	SET_USER: "SET_USER",

	OPEN_MODAL: "OPEN_MODAL",
	CLOSE_MODAL: "CLOSE_MODAL",

	UPDATE_MODAL_INPUT_VALUE: "UPDATE_MODAL_INPUT_VALUE",

	CREATE_COMMENT: "CREATE_COMMENT",
	UPDATE_COMMENT: "UPDATE_COMMENT",
	DELETE_COMMENT: "DELETE_COMMENT",
	CREATE_COMMENT_ERROR: "CREATE_COMMENT_ERROR",
	UPDATE_COMMENT_ERROR: "UPDATE_COMMENT_ERROR",
	DELETE_COMMENT_ERROR: "DELETE_COMMENT_ERROR",

	CREATE_CATEGORY: "CREATE_CATEGORY",
	UPDATE_CATEGORY: "UPDATE_CATEGORY",
	DELETE_CATEGORY: "DELETE_CATEGORY",

	CREATE_SUBCATEGORY: "CREATE_SUBCATEGORY",
	UPDATE_SUBCATEGORY: "UPDATE_SUBCATEGORY",
	DELETE_SUBCATEGORY: "DELETE_SUBCATEGORY",

	CREATE_PRODUCT: "CREATE_PRODUCT",
	UPDATE_PRODUCT: "UPDATE_PRODUCT",
	DELETE_PRODUCT: "DELETE_PRODUCT",

	SET_CATEGORIES: "SET_CATEGORIES",
	SET_CATEGORIES_TITLE: "SET_CATEGORIES_TITLE",
	SET_CATEGORIES_ERROR: "SET_CATEGORIES_ERROR",
	SET_CATEGORIES_LOADING_STATUS: "SET_CATEGORIES_LOADING_STATUS",

	SET_SUBCATEGORIES: "SET_SUBCATEGORIES",
	SET_SUBCATEGORIES_TITLE: "SET_SUBCATEGORIES_TITLE",
	SET_SUBCATEGORIES_ERROR: "SET_SUBCATEGORIES_ERROR",
	SET_SUBCATEGORIES_LOADING_STATUS: "SET_SUBCATEGORIES_LOADING_STATUS",

	SET_PRODUCTS: "SET_PRODUCTS",
	SET_PRODUCTS_TITLE: "SET_PRODUCTS_TITLE",
	SET_PRODUCTS_ERROR: "SET_PRODUCTS_ERROR",
	SET_PRODUCTS_LOADING_STATUS: "SET_PRODUCTS_LOADING_STATUS",

	SET_PRODUCT: "SET_PRODUCT",
	SET_PRODUCT_ERROR: "SET_PRODUCT_ERROR",
	SET_PRODUCT_LOADING_STATUS: "SET_PRODUCT_LOADING_STATUS",

	ADD_PRODUCT_IN_BASKET: "ADD_PRODUCT_IN_BASKET",
	DELETE_PRODUCT_FROM_BASKET: "DELETE_PRODUCT_FROM_BASKET",

	CHANGE_NUMBER_OF_PRODUCTS: "CHANGE_NUMBER_OF_PRODUCTS",

	CREATE_ORDER: "CREATE_ORDER",
};
