export const ACTION_TYPE = {
	LOGOUT: "LOGOUT",
	SET_USER: "SET_USER",
	SET_USER_SESSION: "SET_SESSION",
	OPEN_MODAL_FORM: "OPEN_MODAL_FORM",
	CLOSE_MODAL_FORM: "CLOSE_MODAL_FORM",
	SET_CATEGORY_DATA: "SET_CATEGORY_DATA",
};
